-- liquibase formatted sql

-- changeset script:1
-- comment: Creation table cliente
create table cliente (
    id integer generated by default as identity,
    direccion varchar(255),
    nombre varchar(255),
    telefono varchar(255),
    primary key (id)
);
--
-- changeset script:2
-- comment: Creation table cuentas
create table cuentas (
    id integer generated by default as identity,
    numero integer not null,
    saldo numeric(38,2),
    id_cliente_fk integer,
    primary key (id)
);
--
-- changeset script:3
-- comment: Creation table movimientos
create table movimientos (
    id integer generated by default as identity,
    fecha timestamp(6),
    valor numeric(38,2),
    id_tipo_movimiento_fk integer,
    id_cuenta_fk integer,
    primary key (id)
);
--
-- changeset script:4
-- comment: Creation table tipos_movimiento
create table tipos_movimiento (
    id integer generated by default as identity,
    tipo varchar(255),
    primary key (id)
);
--
-- changeset script:11
-- comment: Creation tipos_movimiento
insert into tipos_movimiento (tipo) values
    ( 'Credito' ),
    ( 'Debito' );
--
-- changeset script:12
-- comment: Creation cliente
insert into cliente (direccion, nombre, telefono) values
    ( 'Calle 5 No 85 - 32', 'Gonzalo Andrade', '3215556699' );
--
-- changeset script:13
-- comment: Creation cuentas
insert into cuentas (id_cliente_fk, numero, saldo) values
    ( 1, 456321, 100 );
--
-- changeset script:14
-- comment: Creation movimientos
insert into movimientos (id_cuenta_fk, id_tipo_movimiento_fk, fecha, valor) values
    ( 1, 1,'2024-01-20 09:00:00', 60 );